Итак, что у нас есть на текущий момент:

* Бизнес-процесс

** Общее описание процесса

   У нас существует несколько складов поставщиков, на которых
   находится товар. Мы закупаем товар у поставщиков, перемещаем его в
   пункты выдачи или прямо доставляем покупателю.

   Пользователь сайта (которым может быть юридическое или физическое
   лицо) выбирает и заказывает товар, оплачивает наличными,
   безналичным расчетом, по карте или с помощью платежной системы,
   забирает товар на пункте выдачи или получает его от службы
   доставки.

   В случае, если товар по какой-либо причине не доставлен
   пользователю мы возвращаем товар на склад.

   Мы отслеживаем перемещения товара, синхронизируем остатки,
   выставляем цены и анализируем продажи.


** Получение заказа

   Изначально мы считаем что нам известно актуальное состояние складов
   поставщиков. Поэтому на сайте мы отображаем только те товары,
   которые у нас есть в наличии. В результате пользователь не может
   заказать товар, которого у нас нет.

   Таким образом, мы можем получить заказ двумя путями:

   + менеджер разговаривает с клиентом по телефону и набивает заказ
     сразу в 1С.

   + клиент сам находит товар на сайте, кладет его в корзину и
     покупает, оформляя заказ.

   Во втором случае сайт самостоятельно обращается к 1С и через
   *интерфейс взаимодействия* создает заказ (без участия менеджера)

   На случай сбоев соединения с 1С сайт поддерживает *очередь
   отправки* для отправляемых заказов и предпринимает попытки
   подключения до получения от интерфейса подтверждения о принятии
   заказа в обработку.

   В случае нескольких (сколько<?>) неудачных попыток в течение
   продолжительного времени заказ переходит в статус *недоставлено -
   сбой связи с 1С* о чем сообщает в лог (и возможно по sms
   разработчику)


** Прохождение заказа

   Получив заказ наша 1С разбивает его на товары и по ним формирует
   заказы к поставщикам, выбирая оптимального по *алгоритму выбора
   оптимального поставщика*. Сформировав заказы, 1С помещает их в
   *очередь отправки* и через нее отправляет заказы нашим
   поставщикам.

   При подключении иных поставщиков (у которых нет такой
   автоматизации) отправкой заказов из очереди занимается специально
   обученный менеджер.


** Резервирование товара на складе

   При получении заказа 1С наших поставщиков автоматически ставит товарные
   позиции в резерв, о чем посылает уведомительное сообщение, чтобы
   на сайте изменилось количество товара.

   Такое сообщение необходимо посылаеть каждый раз, когда количество
   свободных остатков на складах поставщиков изменяется


* Взаимодействие нашего (самописного) сайта и нашей 1С

В документе по протоколу обмена 1С с сайтом
(http://v8.1c.ru/edi/edi_stnd/131/) написано про то, что инициатором
обмена выступает система "1С:Предприятие". Для нашего бизнес-процесса
важно чтобы после заказа на сайте у нас в 1С АВТОМАТИЧЕСКИ
формировался 1С- заказ.

Вероятно технически это связано с тем, что в состав 1С не входит
веб-сервер. В этом случае вопрос - насколько часто 1С может опрашивать
сайт с тем, чтобы забирать заказы как можно быстрее? Какие ограничения
существуют на кол-во передаваемых данных?

В нашем бизнес-процессе пользователь может узнавать о статусе
прохождения его заказа (на складе, в пути, на пункте выдачи и.т.п.)
Что необходимо сделать, чтобы заложить эту возможность?

* Автоматизация прохождения заказа внутри нашей 1С

Допустим у нас есть формализованный алгоритм, согласно которому мы
выбираем поставщика. Можно ли исключить тогда из этого процесса
человека, чтобы появляение У НАС заказа с сайта автоматически
приводило к созданию заказа У ПОСТАВЩИКА? Как это реализовать
технически?

* Взаимодействие между нашей 1С и 1С поставщиков

Каким (техническим) образом могут общаться 1С между собой? Как нам
обеспечить автоматическое и своевременное формирование заказа у наших
поставщиков с минимальными изменениями в их 1С.

Каким образом мы можем получать изменения (отгрузка, резервирование,
приход, возврат из резерва и.т.п) по складам поставщиков в режиме
мягкого реального времени?

* Взаимодействие между нашим (самописным) сайтом и 1С поставщиков. Резерв.

Нам необходимо в реальном времени получать свободные остатки со
складов поставщиков, чтобы правильно представлять товарные позиции на
сайте. В идеале - чтобы в момент, когда у них происходит отгрузка или
резервирование (или наоборот - возврат из резерва) - мы получали
информацию о том что кол-во товара изменилось.

Возможно ли это сделать чтобы данные выгружались напрямую на сайт, или
лучше чтобы они проходили через нашу 1С? (Мне второй вариант кажется
более логичным, но менее быстрым)

* Создание дополнительных полей в карточке товара и группы.

Возможно ли хранить в 1С пользовательские характеристики товара,
разные для разных групп товаров? К примеру, хранить скорость вращения
для вентиляторов или размер экрана для телевизоров так, чтобы в
карточке вентилятора поле "размер экрана" не присутствовало.

Аналогичный вопрос для карточки группы - возможно нам также придется
хранить для некоторых групп дополнительные данные для фильтров на
сайте.

Возможно по этому вопросу есть скрин-каст или запись демонстрации?

Если это задача решаема мы могли бы хранить все данные по товару
(например товары-аналоги или иноформацию о совместимости с другими
изделиями) в одном источнике.

* Масштабирование

Какие существуют подходы, чтобы обойти ограничения по
производительности?

* Обмен данными на низком уровне

Возможен ли обмен данными средствами подлежащей архитектуры
(репликация базы данных PostrgeSQL например). Можем ли мы настроить
репликацию базы данных Master-Slave на другой сервер с тем, чтобы
извлекать оттуда информацию по остаткам и заказам не нагружая этой
работой сервер 1С?

* Обмен данных через УРИБ

Где можно подробнее узнать про УРИБ в разрезе получения остатков -
оформления заказов? Может быть есть технические руководства?

* Коннекторы с Битрикс

Как можно узнать протоколы взаимодействия, через которые производится
обмен данными между 1С и Битрикс, чтобы реализовать их для своего
сайта. Интересуют прежде всего свободные остатки по складам, этапы
прохождения заказа (для отслеживания статуса заказа) и тому подобные
вещи.

* Штрих-коды и RFID

Каким образом можно автоматизировать ручные операции по приемке и
передаче товара в пункты выдачи? Также интересуют варианты с
автоматической печатью всех необходимых документов (путевой лист, ТТН
и.т.п.)

* Тонкий клиент на пунктах выдачи

Хотелось бы узнать ограничения и преимущества использования тонкого
клиента на пунктах выдачи (и на других рабочих местах).

В случае использования толстых клиентов как разрешаются коллизии
(например: бронь клиента сделанная в одном рабочем месте, которую
кто-то снял или продал в другом рабочем месте). Как обеспечивается
безопасность данных (с т.з раскрытия), если пункт выдачи знает о всей
базе данных товаров всех поставщиков?

* Моделирование

Хотелось бы возможно раньше встретиться в присутствии технических
специалистов и смоделировать весь бизнес-процесс с участием модели
складов поставщиков, нашей 1С и сайта и рассмотреть все возникшие
сценарии взаимодействия, чтобы в результате сформулировать список
требований и приступить к планированию решения

* Контакты

Глухов Михаил, IT-директор RAVTA
+7 (911) 286 92 90
m.gluhov@ravta.ru
jabber: i.am.rigidus@jabber.ru (можно добавлять в qip)
skype: i.am.rigidus


