* Вопросы требующие уточнения по стоимости и срокам:

** Стоимость решения (лицензии, etc)
** Стоимость и время настроек и доработок
** Стоимость интеграции (включая моделирование поставщиков)
** Лист требований


* Сценарии

** Мы получаем в свою 1С все остатки и цены поставщиков по складам поставщиков

   Для каждого товара мы заводим уникальный наш артикул

   Мы также храним уникальные идентификаторы товаров для каждого
   поставщика

   Для каждого поставщика нужна обработка которая выгружает остатки в
   xml или текстовый файл и xls.

** Склад поставщика продает кому-то товар

   При:

   + перемещении
   + продаже
   + возвращении из резерва
   + постановке в резерв
   + списании
   + оприходовании
   + изменении цены
   + создании товара в номенклатуре
   + удалении товара из номенклатуры

   поставщик вызывает процедуру из модуля, которая формирует документ
   с уникальным идентификатором товара (обычно артикул поставщика +
   наименование), остатком и ценой. Документ сохраняем как файл в
   специальном каталоге.

   Документ отправляется на сайт по http асинхронно (через планировщик
   1С - регламентные задания), чтобы http-запрос не тормозил отрисовку
   форм у поставщиков.

** Выгрузка остатков с сайта в нашу 1С

   Сайт посылает SOAP-запрос в нашу 1С, запрос содержит адрес, по
   которому 1С скачивает тот же файл, который пришел к нам от
   поставщиков. Потом 1С парсит файл и обновляет данные.


** Прохождение заказа

   Наша 1С постоянно опрашивает сайт, если на сайте есть заказ - сайт
   сообщает об этом в ответе. Данные для передачи берем из формы
   заказа.

   1С Поставщиков постоянно опрашивает сайт и получает заказ.

   Если в течении тайм-периода поставщик не взял заказ - мы звоним им
   и просим починить систему или проводим заказ вручную.


